/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientesPantallas;

import Sucursales.ListasDePrecios;
import facturacion.clientes.Clientes;
import facturacion.pantallas.IngresoDeFacturas;
import facturacion.pantallas.NotaDeCredito;
import facturacion.pantallas.NotaDeDebito;
import interfacesPrograma.Facturar;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author hernan
 */
public class NuevoCliente extends javax.swing.JInternalFrame {

    private ArrayList listadoL = new ArrayList();
    private int originario;
    private Clientes cli;
    private int modificacion;
    private ArrayList listadoPrecios;
    private ListasDePrecios lista;

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        modificacion = 0;
        listadoPrecios = new ArrayList();

        listadoPrecios = ListasDePrecios.Listado();
        Iterator itL = listadoPrecios.listIterator();
        while (itL.hasNext()) {
            lista = (ListasDePrecios) itL.next();
            this.lst_precios_comb.addItem(lista.getDesccripcion());
        }
    }

    public NuevoCliente(int origen) {
        initComponents();
        originario = origen;
        cli = new Clientes();
        modificacion = 0;
        listadoPrecios = new ArrayList();

        listadoPrecios = ListasDePrecios.Listado();
        Iterator itL = listadoPrecios.listIterator();
        int posi=0;
        int selecP=0;
        while (itL.hasNext()) {
            lista = (ListasDePrecios) itL.next();
            this.lst_precios_comb.addItem(lista.getDesccripcion());
            
        }
        
    }

    public NuevoCliente(int origen, Clientes cliente) {
        initComponents();
        originario = origen;
        cli = cliente;
        this.jTextField1.setText(cli.getRazonSocial());
        this.jTextField2.setText(cli.getDireccion());
        this.jTextField3.setText(cli.getNumeroDeCuit());
        this.jTextField4.setText(cli.getTelefono());
        if (cli.getCupoDeCredito() == 0) {
            this.jCheckBox1.setSelected(false);
        } else {
            this.jCheckBox1.setSelected(true);
        }
        modificacion = 1;
        int posicion = 0;
        int tipo = cli.getTipoIva();
        switch (tipo) {
            case 5:
                posicion = 0;
                break;
            case 1:
                posicion = 1;
                break;
            case 4:
                posicion = 2;
                break;
            case 6:
                posicion = 3;
                break;

        }
        this.jComboBox2.setSelectedIndex(posicion);
         listadoPrecios = new ArrayList();

        listadoPrecios = ListasDePrecios.Listado();
        Iterator itL = listadoPrecios.listIterator();
        int posi=0;
        int selecP=0;
        while (itL.hasNext()) {
            lista = (ListasDePrecios) itL.next();
            this.lst_precios_comb.addItem(lista.getDesccripcion());
            if(cli.getListaDePrecios()==lista.getId())selecP=posi;
            posi++;
        }
        this.lst_precios_comb.setSelectedIndex(selecP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        lst_precios_comb = new javax.swing.JComboBox();

        setClosable(true);
        setResizable(true);
        setTitle("FACTURACION - CARGA DE NUEVO CLIENTE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Mlogo.png"))); // NOI18N

        jLabel1.setText("Razon Social");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setText("Domicilio :");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel4.setText("N° de CUIT:");

        jTextField3.setText("0");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jLabel5.setText("Telefono :");

        jTextField4.setText("0");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevos/guardar.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Cond IVA");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consumidor Final", "Responsable Inscripto", "Exento", "Monotributo" }));

        jCheckBox1.setText("Habilita Cta Cte ?");

        jLabel7.setText("Lista de Precio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jComboBox2, 0, 297, Short.MAX_VALUE)
                            .addComponent(lst_precios_comb, 0, 297, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lst_precios_comb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //cli.setCodigoCliente(title);
        cli.setRazonSocial(this.jTextField1.getText());
        cli.setDireccion(this.jTextField2.getText());
        String condicion = "1";
        //Double limite=Numeros.ConvertirStringADouble(this.jTextField5.getText());
        //cli.setCupoDeCredito(limite);
        //if(limite > 0){
        //    cli.setCondicionDeVenta(2);
        //}else{
        cli.setCondicionDeVenta(1);
        //}
        cli.setEmpresa("bu");
        int tipoIva = 0;
        switch (this.jComboBox2.getSelectedIndex()) {
            case 0:
                tipoIva = 5;
                break;
            case 1:
                tipoIva = 1;
                break;
            case 2:
                tipoIva = 4;
                break;
            case 3:
                tipoIva = 6;
                break;
        }
        condicion = String.valueOf(tipoIva);
        //ListasDePrecios lista=new ListasDePrecios();
        int posLista = this.lst_precios_comb.getSelectedIndex();
        
        lista=(ListasDePrecios)listadoPrecios.get(posLista);
        //lista=new 
        cli.setListaDePrecios(lista.getId());
        cli.setCoeficienteListaDeprecios(lista.getCoeficiente());
        /*
       if(cli.getCupoDeCredito() > 0.00){
           cli.setCondicionDeVenta(2);
       }else{
        cli.setCondicionDeVenta(1);
       }
         */
        //cli.setCoeficienteListaDeprecios(1.00);
        cli.setCondicionIva(condicion);
        cli.setTipoIva(tipoIva);
        if (this.jCheckBox1.isSelected()) {
            cli.setCupoDeCredito(1.00);
        } else {
            cli.setCupoDeCredito(0.00);
        }
        cli.setNumeroDeCuit(this.jTextField3.getText().replace("-", "").trim());
        cli.setTelefono(this.jTextField4.getText());
        Facturar fact = new Clientes();
        if (modificacion == 0) {
            cli.setCodigoId(fact.guardarNuevoCliente(cli));
        } else {
            fact.modificarDatosDelCliente(cli);
        }
        cli.setCodigoCliente(String.valueOf(cli.getCodigoId()));

        if (originario == 1) {
            if (cli.getCupoDeCredito() == 0) {
                IngresoDeFacturas.jCheckBox2.setSelected(true);
                IngresoDeFacturas.jCheckBox2.setEnabled(false);
            } else {
                IngresoDeFacturas.jCheckBox2.setSelected(false);
                IngresoDeFacturas.jCheckBox2.setEnabled(true);
            }
            IngresoDeFacturas.cliT = cli;
            IngresoDeFacturas.jLabel6.setText(cli.getRazonSocial());
            IngresoDeFacturas.jTextField1.requestFocus();
            this.dispose();
        }
        if (originario == 2) {
            if (cli.getCupoDeCredito() == 0) {
                NotaDeCredito.jCheckBox2.setSelected(true);
                NotaDeCredito.jCheckBox2.setEnabled(false);
            } else {
                NotaDeCredito.jCheckBox2.setSelected(false);
                NotaDeCredito.jCheckBox2.setEnabled(true);
            }
            NotaDeCredito.cliT = cli;
            NotaDeCredito.jLabel6.setText(cli.getRazonSocial());
            NotaDeCredito.jTextField1.requestFocus();
            this.dispose();
        }
        if (originario == 3) {
            if (cli.getCupoDeCredito() == 0) {
                NotaDeDebito.jCheckBox2.setSelected(true);
                NotaDeDebito.jCheckBox2.setEnabled(false);
            } else {
                NotaDeDebito.jCheckBox2.setSelected(false);
                NotaDeDebito.jCheckBox2.setEnabled(true);
            }
            NotaDeDebito.cliT = cli;
            NotaDeDebito.jLabel6.setText(cli.getRazonSocial());
            NotaDeDebito.jTextField1.requestFocus();
            this.dispose();
        }
        if (originario == 4) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jTextField4.requestFocus();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox lst_precios_comb;
    // End of variables declaration//GEN-END:variables
}
