/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Articulos.Pantallas;

import Articulos.ColumnasExcel;
import Articulos.LeerExcel;
import Articulos.Modelable;
import Conversores.Numeros;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

/**
 *
 * @author mauro
 */
public class AbmIva extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmIva
     */
    public AbmIva() {
        initComponents();
        this.jFileChooser1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Importar Excell");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Mlogo.png"))); // NOI18N

        jFileChooser1.setDialogTitle("Seleccion de Origen de Datos");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevos/procesar.png"))); // NOI18N
        jButton3.setText("Procesar Archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        File fichero;
        int resultado;
        this.jFileChooser1.setVisible(true);
        
        //FileNameExtensionFilter filtro = new FileNameExtensionFilter("txt","pdf");
        //this.jFileChooser1.setFileFilter(filtro);
        resultado=this.jFileChooser1.showOpenDialog(this);
        String seleccionado = null;
        if (JFileChooser.APPROVE_OPTION == resultado){

            fichero = this.jFileChooser1.getSelectedFile();
            seleccionado=fichero.getPath();
            System.out.println(seleccionado);
            
            VerArchivo ver=new VerArchivo(null,true,fichero);
            ver.setVisible(true);
        /*
        LeerExcel leer=new LeerExcel();
        ArrayList columm=leer.LeerColumnas(seleccionado);
        ArrayList enviarC=new ArrayList();
        ColumnasExcel exCol;
        SelectorDeColumnas selC=new SelectorDeColumnas();
        Modelable mod=new ColumnasExcel();
        DefaultComboBoxModel modeloo=new DefaultComboBoxModel();
        modeloo=mod.MostrarEnCombo(columm);
        selC.jComboBox1.setModel(modeloo);
        selC.jComboBox3.setModel(mod.MostrarEnCombo(columm));
        selC.jComboBox6.setModel(mod.MostrarEnCombo(columm));
        selC.jComboBox7.setModel(mod.MostrarEnCombo(columm));
        //selC.jComboBox4.setModel(mod.MostrarEnCombo(columm));
        //selC.jComboBox5.setModel(mod.MostrarEnCombo(columm));
        selC.setVisible(true);
        selC.toFront();
        Double porcentaje=0.00;
        Double bonificacion=0.00;
        int sele=0;
        if(selC.confirmado==1){
        exCol=new ColumnasExcel();
        sele=selC.jComboBox1.getSelectedIndex();
        exCol=(ColumnasExcel) columm.get(sele);
        exCol.setNombreDato("BARRAS");
        enviarC.add(exCol);
        sele=selC.jComboBox3.getSelectedIndex();
        exCol=new ColumnasExcel();
        exCol=(ColumnasExcel) columm.get(sele);
        exCol.setNombreDato("NOMBRE");
        enviarC.add(exCol);
        sele=selC.jComboBox6.getSelectedIndex();
        exCol=new ColumnasExcel();
        exCol=(ColumnasExcel) columm.get(sele);
        exCol.setNombreDato("COSTO");
        enviarC.add(exCol);
        sele=selC.jComboBox7.getSelectedIndex();
        exCol=new ColumnasExcel();
        exCol=(ColumnasExcel) columm.get(sele);
        exCol.setNombreDato("PRECIO");
        enviarC.add(exCol);
        
        System.out.println(selC.jComboBox1.getSelectedIndex()+" -- "+selC.jComboBox3.getSelectedIndex()+" -- "+selC.jComboBox6.getSelectedIndex());
        porcentaje=0.00;//Numeros.ConvertirStringADouble(selC.jTextField1.getText());
        porcentaje=Numeros.ConvertirEnCoeficiente(porcentaje);
        bonificacion=0.00;//Numeros.ConvertirStringADouble(selC.jTextField2.getText());
        bonificacion=Numeros.ConvertirEnDescuento(bonificacion);
        int ivva=0;
        int origen=0;
        
        exCol=(ColumnasExcel) columm.get(0);
        if(exCol.getId()!=null){
            
            leer.leerExcel1(seleccionado,enviarC,porcentaje,ivva,origen,bonificacion);
            
            this.dispose();
        }
        }  
        
        */
        }
        
        /*
        String period=null;
        if(JOptionPane.showConfirmDialog(this,"Procesa el archivo seleccionado?","Aplicar Origen",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==1){
        }else{
        LeerIva iva=new LeerIva();
        period=JOptionPane.showInputDialog(this,"Ingrese periodo");
        iva.leerArchivo(seleccionado,period);
        }
        */
        /*
        LeerExcel leer=new LeerExcel();
        try {
        leer.leerExcel1("SubIva/iva ventas marzo2.xls");
        } catch (SQLException ex) {
        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
        /*
        if(JOptionPane.showConfirmDialog(this,"Genera el pdf del periodo Procesado?","Generar PDF",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==1){
        }else{
        
        if(period!=null){
        
        }else{
        period=JOptionPane.showInputDialog(this,"Ingrese periodo");
        }
        pdfsJavaGenerador pd=new pdfsJavaGenerador();
        pd.setPeriodo(period);
        pd.run();
        
        }
        this.jFileChooser1.setVisible(false);
        
        */
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
