package Articulos;



import Conversores.Numeros;
import Sucursales.ListasDePrecios;
import interfaceGraficas.Inicio;
import interfaces.Personalizable;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mauro di
 */
public class AbmArticulos extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo1=new DefaultTableModel();
    private DefaultTableModel modelo2=new DefaultTableModel();
    private DefaultTableModel modelo3=new DefaultTableModel();
    private ArrayList listadoSeleccion=new ArrayList();
    private ArrayList listadoRubros=new ArrayList();
    private ArrayList listadoSubRubros=new ArrayList();
    private ArrayList listadoGral=new ArrayList();
    private Articulos articulos;
    private ListasDePrecios listaDePrecios;
    private ArrayList listadoDePrecios=new ArrayList();
    private static Rubrable sRble=new SubRubros();
    private TableColumn columna;
    private TableColumn columna1;
    private TableColumn columna2;
    private TableColumn columna3;
    
    
    
    /**
     * Creates new form ListasPorCliente
     */
    public AbmArticulos() {
        
        initComponents();
        
        Rubros rubro=new Rubros();
        Rubrable rble=new Rubros();
        listadoRubros=rble.listarPorRubro(0);
        
        modelo2=rble.mostrarListado(listadoRubros);
        Modificable artis=new Articulos();
        listadoGral=artis.buscar(0,0,"");
        System.out.println("CANTIDAD: "+listadoGral.size());
        modelo1=artis.mostrarListado(listadoGral);
        this.jTable1.setModel(modelo1);
        this.jTable2.setModel(modelo2);
        columna=this.jTable1.getColumn("Listar");
        columna.setPreferredWidth(50);
        columna.setMaxWidth(50);
        
        columna1=this.jTable1.getColumn("Precio");
        columna1.setPreferredWidth(70);
        columna1.setMaxWidth(70);
        columna2=this.jTable1.getColumn("Costo");
        columna2.setPreferredWidth(70);
        columna2.setMaxWidth(70);
        columna3=this.jTable1.getColumn("% de Ganancia");
        columna3.setPreferredWidth(80);
        columna3.setMaxWidth(80);
        columna=this.jTable2.getColumn("Seleccion");
        columna.setPreferredWidth(50);
        columna.setMaxWidth(50);
        this.jTable3.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificacion de Artículos");

        jTable2.setModel(modelo2);
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setText("Filtrar por Rubros - Seleccione o des seleccione los rubros a incluir // Para subRubros - seleccione y luego presione F1 - Para seleccionar/ des seleccionar F2");

        jTable3.setModel(modelo3);
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("Modificar Articulo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("0.00");

        jLabel1.setText("Precio de venta:");

        jLabel2.setText("Precio de costo:");

        jTextField2.setText("0.00");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/folder_new.png"))); // NOI18N
        jButton3.setText("Nuevo Articulo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Porcentaje de Ganancia:");

        jTextField3.setText("0.00");

        jCheckBox1.setText("Valor");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Porcentaje");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jCheckBox2))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jCheckBox1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTable1.setModel(modelo1);
        jTable1.setMinimumSize(new java.awt.Dimension(600, 200));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int cantidad=this.jTable1.getSelectedRow();
        Articulos articulos=new Articulos();
        articulos=(Articulos)listadoGral.get(cantidad);
        ArticulosMod mod=new ArticulosMod(articulos);
        Inicio.jDesktopPane1.add(mod);
        try {
            mod.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AbmArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        mod.setVisible(true);
        mod.toFront();
        /*
        Boolean selec;
        for (int a=0;a < cantidad;a++){
            selec=(Boolean) this.jTable1.getValueAt(a, 0);
            if(selec){
            articulos=(Articulos)listadoGral.get(a);
            listadoSeleccion.add(articulos);
            }
        }
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
        ArrayList lls=new ArrayList();
        int ctt=this.jTable2.getRowCount();
        
        SubRubros subRubro=new SubRubros();
        //Rubrable sRble=new SubRubros();
        Rubros rubro;
        Boolean ss;
        for (int aa=0;aa < ctt;aa++){
            
            ss=(Boolean)this.jTable2.getValueAt(aa,0);
            if(ss){
                rubro=new Rubros();
                rubro=(Rubros)listadoRubros.get(aa);
                lls.add(rubro);
            }
        }
        Modificable att=new Articulos();
        
        listadoSubRubros.clear();
        listadoSubRubros=sRble.listarPorSubRubro(lls);
        
        modelo3=sRble.mostrarListado(listadoSubRubros);
        listadoGral=att.filtrador(listadoSubRubros, lls);
        modelo1=att.mostrarListado(listadoGral);
        Double porcentajeGanancia=0.00;
        porcentajeGanancia=Articulos.getTotalVenta() / Articulos.getTotalCosto();
        System.err.println("vta "+Articulos.getTotalVenta()+" costo "+Articulos.getTotalCosto()+" total "+porcentajeGanancia);
        porcentajeGanancia=(porcentajeGanancia -1) * 100;
         
        this.jTextField3.setText(String.valueOf(Math.round(porcentajeGanancia)));
        this.jTable3.setVisible(true);
        this.jTable3.setModel(modelo3);
        
        this.jTable1.setModel(modelo1);
        columna=this.jTable1.getColumn("Listar");
        columna.setPreferredWidth(50);
        columna.setMaxWidth(50);
        
        columna1=this.jTable1.getColumn("Precio");
        columna1.setPreferredWidth(70);
        columna1.setMaxWidth(70);
        columna2=this.jTable1.getColumn("Costo");
        columna2.setPreferredWidth(70);
        columna2.setMaxWidth(70);
        columna3=this.jTable1.getColumn("% de Ganancia");
        columna3.setPreferredWidth(80);
        columna3.setMaxWidth(80);
        columna=this.jTable3.getColumn("Seleccion");
        columna.setPreferredWidth(50);
        columna.setMaxWidth(50);
    }//GEN-LAST:event_jTable2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //listaDePrecios=(ListasDePrecios)listadoDePrecios.get(this.jComboBox3.getSelectedIndex());
        Double coeficiente=Numeros.ConvertirStringADouble(this.jTextField1.getText());
        Double coeficiente1=Numeros.ConvertirStringADouble(this.jTextField2.getText());
        Double ganancia=Numeros.ConvertirStringADouble(this.jTextField3.getText());
        //String observaciones=JOptionPane.showInputDialog(this,"Ingrese comentario");
        
            //coeficiente=listaDePrecios.getCoeficiente();
        
        Modificable att=new Articulos();
        Articulos articulo=new Articulos();
        
        ArrayList resultado=new ArrayList();
        int renglones=this.jTable1.getRowCount();
        for(int a = 0;a < renglones;a++){
            if((Boolean) this.jTable1.getValueAt(a, 0)){
                articulo=(Articulos)listadoGral.get(a);
                articulo.setConfirmado(true);
            //articulo.setCoeficiente(coeficiente);
            //articulo.setIdLista(listaDePrecios.getId());
            //articulo.setObservaciones(observaciones);
            resultado.add(articulo);
            articulo.setConfirmado(false);
            }
        }
        
        if(coeficiente==0.00 && coeficiente1==0.00){
            att.aplicarGanancia(resultado, ganancia);
        }else{
            if(this.jCheckBox1.isSelected()){
                int seleccion1=JOptionPane.showOptionDialog(this,"¿desea modificar el precio por valor?", "Seleccione una opcion", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[]{"Si","No"}, "Si");
                 if (seleccion1 != -1)resultado=att.modificarPreciosValor(resultado, coeficiente, coeficiente1);
            }else{
               resultado=att.modificarPrecios(resultado, coeficiente, coeficiente1);
            }
            if(coeficiente1 > 0){
                int seleccion=JOptionPane.showOptionDialog(this,"¿desea aplicar el porcentaje de ganancia al costo ingresado?", "Seleccione una opcion", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[]{"Si","No"}, "Si");
                if (seleccion != -1)
{
   if((seleccion + 1)==1)
   {
      att.aplicarGanancia(resultado, ganancia);
   }

}
            }
        }
        //listadoGral=resultado;
        
        modelo1=att.actualizarListado(listadoGral);
        this.jTable1.setModel(modelo1);
        columna=this.jTable1.getColumn("Descripcion");
        columna.setPreferredWidth(400);
        this.jTextField1.setText("0.00");
        this.jTextField2.setText("0.00");
        
//att.guardar(resultado);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyPressed
        
        if(evt.getKeyCode()==KeyEvent.VK_F1){
            ArrayList provisorio=new ArrayList();
        int cantidad=this.jTable3.getRowCount();
        for(int b=0;b < cantidad;b++){
            if((Boolean)this.jTable3.getValueAt(b, 0)){
            provisorio.add(listadoSubRubros.get(b));
        }
            
        }
        Modificable att=new Articulos();
        listadoGral=att.filtrador(provisorio,provisorio);
        //listadoGral=att.filtrador(listadoSubRubros, listadoSubRubros);
        modelo1=att.mostrarListado(listadoGral);
         modelo3=sRble.mostrarListado(listadoSubRubros);
         Double porcentajeGanancia=0.00;
         porcentajeGanancia=Articulos.getTotalVenta() / Articulos.getTotalCosto();
         porcentajeGanancia=(porcentajeGanancia -1) * 100;
        this.jTextField3.setText(String.valueOf(Math.round(porcentajeGanancia)));
         this.jTable3.setModel(modelo3);
         this.jTable1.setModel(modelo1);
         columna=this.jTable1.getColumn("Listar");
        columna.setPreferredWidth(50);
        columna.setMaxWidth(50);
        
        columna1=this.jTable1.getColumn("Precio");
        columna1.setPreferredWidth(70);
        columna1.setMaxWidth(70);
        columna2=this.jTable1.getColumn("Costo");
        columna2.setPreferredWidth(70);
        columna2.setMaxWidth(70);
        columna3=this.jTable1.getColumn("% de Ganancia");
        columna3.setPreferredWidth(80);
        columna3.setMaxWidth(80);
        this.jTable1.requestFocus();
    }
    }//GEN-LAST:event_jTable3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArticulosMod articMo=new ArticulosMod();
        Inicio.jDesktopPane1.add(articMo);
        articMo.setVisible(true);
        articMo.toFront();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        int cantidad=this.jTable1.getRowCount();
        if(evt.getKeyCode()==KeyEvent.VK_F2){
            for(int b=0;b < cantidad;b++){
            if((Boolean)this.jTable1.getValueAt(b, 0)){
                this.jTable1.setValueAt(false, b,0);
        }else{
                this.jTable1.setValueAt(true, b,0);
            }
        }
        }else{
        ArrayList resTado=new ArrayList();
        Articulos articu;
        for(int b=0;b < cantidad;b++){
            if((Boolean)this.jTable1.getValueAt(b, 0)){
            articu=new Articulos();
            articu=(Articulos)listadoGral.get(b);
            resTado.add(articu);
        }else{
                //listadoGral.remove(b);
            }
        }
        Modificable att=new Articulos();
        att.depurarFiltrador(resTado);
        //listadoGral=att.filtrador(listadoSubRubros, listadoSubRubros);
        
        //modelo1=att.mostrarListado(listadoGral);
        
         //modelo3=sRble.mostrarListado(listadoSubRubros);
        
         Double porcentajeGanancia=0.00;
         Double totalV=Articulos.getTotalVenta();
         Double totalC=Articulos.getTotalCosto();
         porcentajeGanancia=totalV / totalC;
         porcentajeGanancia=(porcentajeGanancia -1) * 100;
        this.jTextField3.setText(String.valueOf(Math.round(porcentajeGanancia)));
        //this.jTable1.setModel(modelo1);
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        if(this.jCheckBox1.isSelected()){
            this.jCheckBox2.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        if(this.jCheckBox2.isSelected()){
            this.jCheckBox1.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
