/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cajas;

import Conversores.Numeros;
import Excel.InformeDiarioStock;
import Impresiones.Impresora;
import Cajas.Cajas;
import interfaceGraficasManantial.Inicio;
import interfacesPrograma.Cajeables;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mauro
 */
public class ArqueoDeCaja extends javax.swing.JInternalFrame {
    private Double totalB;
    /**
     * Creates new form ArqueoDeCaja
     */
    public ArqueoDeCaja() {
        initComponents();
        totalB=0.00;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Arqueo de Caja");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Mlogo.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevos/cerrar.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        /*
         * ACA ALGO ESTA MAL
         * 1- DEBO CARGAR EL MOVIMIENTO DE ENTREGA DE SALDO
         * 2- GENERAR UNA VISTA CON EL TOTAL DE MOVIMIENTOS DE CAJA
         * 3- DE AHI SALE LA DIFERENCIA DE CAJA QUE ES LO QUE TENGO QUE GRABAR EN LA BASE
         * 4- ESE VA A SER EL SALDO FINAL
         * 
         */
        
        Double saldoInicial=0.00;
        Double saldoFinal=0.00;
        Double diferencia=0.00;
        Double entrega=0.00;
        saldoInicial=Inicio.sucursal.getCaja().getSaldoInicial();
        saldoFinal=totalB - saldoInicial;
        Cajeables caj=new Cajas();
        Cajas cajas=new Cajas();
        cajas=(Cajas)caj.ArquearCaja(Inicio.sucursal.getCaja());
        Double totalMovimientos=(Double)cajas.getSaldoFinal();
        diferencia=saldoFinal - totalMovimientos;
        //cajas.setMontoMovimiento(diferencia);
        entrega=0.00;
        //entrega=entrega * -1;
        cajas.setMontoMovimiento(entrega);
        diferencia=0.00;
        cajas.setSaldoFinal(totalB);
        /*
         * OJO ACA ES DONDE ESTA CALCULANDO MAL, EN ALGUN PUNTO ME ESTA SUMANDO AL SALDO EN CAJA
         * TODO EL MONTO DE TOTALB + EL MONTO A RETIRAR Y NO MUESTRA EL SALDO EN CAJA
         * PUEDE QUE SEA EL - QUE BA PUESTO, LO CAMBIE POR UN +
         * 
         */
        
        Double quedaEnCaja=0.00;//totalB + entrega;
        
        cajas.setCambioEnCaja(quedaEnCaja);
        
        cajas.setTotalVentas(totalB);
        
        
        caj.CerrarCaja(cajas);
        caj.ArquearCaja(Inicio.caja);
        Impresora impresion=new Impresora();
        impresion.ImprimirCierreDeCaja(Cajas.getListadoCajas());
        this.dispose();
        //ACA DEBE EMITIR EL INFORME DE STOCK PARA CONTROL Y MANDAR EL MAIL CON EL MISMO INFORME
        InformeDiarioStock info=new InformeDiarioStock();
        try {
            info.GenerrarInformeStock();
        } catch (SQLException ex) {
            Logger.getLogger(ArqueoDeCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.exit(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
