/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedores;

import Citi.objetosDao.ComprasfiscalJpaController;
import Conversores.Numeros;
import Proveedores.Interfaces.FacturableE;
import Proveedores.objetos.MovimientoProveedores;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetosCiti.Comprasfiscal;

/**
 *
 * @author hernan
 */
public class IngresoFcProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresoDePedidos
     */
    public Proveedores cliT;
    private Comprasfiscal compras;
    private ComprasfiscalJpaController controlador;
    private double montoTotal;
    private String alicuotaIva;

    public IngresoFcProveedor(Proveedores clienteTango) {
        //cliT=new Clientes();
        cliT = (Proveedores) clienteTango;
        //lista=new ListasDePrecios(cliT.getListaDePrecios());
//cliT=(ClientesTango)oob;
        //comp.setCliente(cliT);
        initComponents();
        montoTotal = 0.00;
        compras = new Comprasfiscal();
        controlador = new ComprasfiscalJpaController();
        alicuotaIva="0005";

    }

    public IngresoFcProveedor(MovimientoProveedores ped, Proveedores clienteTango) {
        //factura=new Facturas();
        MovimientoProveedores pedido = new MovimientoProveedores();
        ArrayList listadoPed = new ArrayList();
        pedido = (MovimientoProveedores) ped;
        alicuotaIva="0005";

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numero_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        punto_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fecha_cmb = new datechooser.beans.DateChooserCombo();
        tipoComprobante_cmb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        montoGravado_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        alicuota_cmb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        montoIva_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        netoNoGravado_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        exento_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        percepcionIva_txt = new javax.swing.JTextField();
        impuestosNacionales_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        percepcionIB_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        impuestosMunicipales_txt = new javax.swing.JTextField();
        impuestosInternos_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        otros_txt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        total_lbl = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingreso de Facturas de Proveedores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Mlogo.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setMaximumSize(new java.awt.Dimension(570, 230));

        jLabel3.setText("Tipo de Comprobante");

        jLabel4.setText("Pto de Venta");

        jLabel7.setText("Numero");

        numero_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numero_txtKeyPressed(evt);
            }
        });

        jLabel2.setText("Fecha Comprobante");

        punto_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                punto_txtKeyPressed(evt);
            }
        });

        tipoComprobante_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACTURA A", "FACTURA B", "FACTURA C", "NTA DE CREDITO A", "NTA DE CREDITO B", "NTA DE CREDITO C" }));
        tipoComprobante_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoComprobante_cmbActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto Gravado");

        montoGravado_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                montoGravado_txtKeyPressed(evt);
            }
        });

        jLabel6.setText("Alícuota de IVA");

        alicuota_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IVA 21%", "IVA 10.5%", "IVA 0%" }));
        alicuota_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alicuota_cmbActionPerformed(evt);
            }
        });

        jLabel9.setText("Monto IVA");

        montoIva_txt.setEnabled(false);
        montoIva_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                montoIva_txtKeyPressed(evt);
            }
        });

        jLabel10.setText("Neto No Gravado");

        netoNoGravado_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                netoNoGravado_txtKeyPressed(evt);
            }
        });

        jLabel11.setText("Monto Exento");

        exento_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exento_txtKeyPressed(evt);
            }
        });

        jLabel12.setText("Monto de Percepcion de IVA");

        percepcionIva_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                percepcionIva_txtKeyPressed(evt);
            }
        });

        impuestosNacionales_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                impuestosNacionales_txtKeyPressed(evt);
            }
        });

        jLabel13.setText("Impuestos Nacionales");

        percepcionIB_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                percepcionIB_txtKeyPressed(evt);
            }
        });

        jLabel14.setText("Percepcion IB");

        jLabel15.setText("Impuestos Municipales");

        impuestosMunicipales_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                impuestosMunicipales_txtKeyPressed(evt);
            }
        });

        impuestosInternos_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                impuestosInternos_txtKeyPressed(evt);
            }
        });

        jLabel16.setText("Impuestos Internos");

        otros_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otros_txtKeyPressed(evt);
            }
        });

        jLabel17.setText("Otros Tributos");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevos/guardar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        total_lbl.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(punto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecha_cmb, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(tipoComprobante_cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numero_txt))
                            .addComponent(montoGravado_txt)
                            .addComponent(alicuota_cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(montoIva_txt)
                            .addComponent(netoNoGravado_txt)
                            .addComponent(exento_txt)
                            .addComponent(percepcionIva_txt)
                            .addComponent(impuestosNacionales_txt)
                            .addComponent(percepcionIB_txt)
                            .addComponent(impuestosMunicipales_txt)
                            .addComponent(impuestosInternos_txt)
                            .addComponent(otros_txt))))
                .addGap(18, 18, 18)
                .addComponent(total_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha_cmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoComprobante_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(punto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(numero_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(montoGravado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(alicuota_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(montoIva_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(netoNoGravado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(exento_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(percepcionIva_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(impuestosNacionales_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(percepcionIB_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(impuestosMunicipales_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(impuestosInternos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(otros_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden

    }//GEN-LAST:event_formComponentHidden

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

    }//GEN-LAST:event_formInternalFrameClosing

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        punto_txt.requestFocus();
    }//GEN-LAST:event_formComponentShown

    private void numero_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.montoGravado_txt.requestFocus();
        }
    }//GEN-LAST:event_numero_txtKeyPressed

    private void punto_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_punto_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.numero_txt.requestFocus();
        }
    }//GEN-LAST:event_punto_txtKeyPressed

    private void montoIva_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoIva_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.montoIva_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.netoNoGravado_txt.requestFocus();
        }
    }//GEN-LAST:event_montoIva_txtKeyPressed

    private void netoNoGravado_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_netoNoGravado_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.netoNoGravado_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.exento_txt.requestFocus();
        }
    }//GEN-LAST:event_netoNoGravado_txtKeyPressed

    private void exento_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exento_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.exento_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.percepcionIva_txt.requestFocus();
        }
    }//GEN-LAST:event_exento_txtKeyPressed

    private void percepcionIva_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percepcionIva_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.percepcionIva_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.impuestosNacionales_txt.requestFocus();
        }
    }//GEN-LAST:event_percepcionIva_txtKeyPressed

    private void impuestosNacionales_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_impuestosNacionales_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.impuestosNacionales_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.percepcionIB_txt.requestFocus();
        }
    }//GEN-LAST:event_impuestosNacionales_txtKeyPressed

    private void percepcionIB_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percepcionIB_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.percepcionIB_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.impuestosMunicipales_txt.requestFocus();
        }
    }//GEN-LAST:event_percepcionIB_txtKeyPressed

    private void impuestosMunicipales_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_impuestosMunicipales_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.impuestosMunicipales_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.impuestosInternos_txt.requestFocus();
        }
    }//GEN-LAST:event_impuestosMunicipales_txtKeyPressed

    private void impuestosInternos_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_impuestosInternos_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.impuestosInternos_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.otros_txt.requestFocus();
        }
    }//GEN-LAST:event_impuestosInternos_txtKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String fecha = Numeros.ConvertirFechaLeidaDeDateChooser(this.fecha_cmb.getSelectedDate());
        String fechaM=fecha;
        int tipoComprobante = this.tipoComprobante_cmb.getSelectedIndex();
        int tipoComp=11;
        int tipoInterno=5;
        double multiplo=1.00;
        switch(tipoComprobante){
            case 0:
              tipoComp=1;
              tipoInterno=5;
              break;
            case 1:
                tipoComp=6;
                tipoInterno=6;
                break;
            case 2:
                tipoComp=11;
                tipoInterno=7;
                break;
            case 3:
                tipoComp=3;
                tipoInterno=8;
                multiplo= -1.00;
                break;
            case 4:
                tipoComp=8;
                tipoInterno=9;
                multiplo= -1.00;
                break;
            case 5:
                tipoComp=13;
                tipoInterno=10;
                multiplo= -1.00;
                break;
        }
        int puntoDeVenta;
        if (this.punto_txt.getText() != null) {
            puntoDeVenta = Integer.parseInt(this.punto_txt.getText());
        } else {
            puntoDeVenta = 1;
        }
        String numero = this.numero_txt.getText().replace("-", "");
        double montoGravado = Numeros.ConvertirStringADouble(this.montoGravado_txt.getText());
        double montoIva = Numeros.ConvertirStringADouble(this.montoIva_txt.getText());
        
    double netoNoGravado=Numeros.ConvertirStringADouble(this.netoNoGravado_txt.getText());
    double exento=Numeros.ConvertirStringADouble(this.exento_txt.getText());
    double percepcionIva=Numeros.ConvertirStringADouble(this.percepcionIva_txt.getText());
    double impuestosNacionales=Numeros.ConvertirStringADouble(this.impuestosNacionales_txt.getText());
    double percepcionIb=Numeros.ConvertirStringADouble(this.percepcionIB_txt.getText());
    double impuestosMunicipales=Numeros.ConvertirStringADouble(this.impuestosMunicipales_txt.getText());
    double impuestosInternos=Numeros.ConvertirStringADouble(this.impuestosInternos_txt.getText());
    double otros=Numeros.ConvertirStringADouble(this.otros_txt.getText());
         
        compras.setFecha(fecha.replace("-",""));
        //String ptoVta=String.format("%05d", this.numeroPuntoDeVenta);
        compras.setTipo(String.format("%03d", tipoComp));
        compras.setPto(String.format("%05d", puntoDeVenta));
        compras.setNumero(String.format("%0" + (20 - numero.length()) + "d%s", 0, numero));
        compras.setGravado(montoGravado);
        compras.setAlicuota("0005");
        compras.setIva(montoIva);
        compras.setNetonogravado(netoNoGravado);
        compras.setExentas(exento);
        compras.setPercepcioniva(percepcionIva);
        compras.setImpuestosnacionales(impuestosNacionales);
        compras.setPercepcionib(percepcionIb);
        compras.setImpmunicipales(impuestosMunicipales);
        compras.setImpinternos(impuestosInternos);
        compras.setOtrostributos(otros);
        montoTotal=montoGravado+montoIva+netoNoGravado+exento+percepcionIva+impuestosNacionales+percepcionIb+impuestosMunicipales+impuestosInternos+otros;
        compras.setTotal(montoTotal);
        compras.setIdcliente(cliT.getNumero());
        compras.setTipoClienteId(cliT.getCondicionDeIva());
        compras.setRazon(cliT.getNombre());
        compras.setCuit(cliT.getCuit());
        compras.setAlicuota(alicuotaIva);
        Integer id=controlador.create(compras);
        String resultado = " Fecha: " + fecha + " tipo " + compras.getTipo() + " punto " + compras.getPto() + " numero " + compras.getNumero();
        
        MovimientoProveedores movi=new MovimientoProveedores();
        movi.setTipoComprobante(tipoInterno);
        movi.setIdProveedor(cliT.getNumero());
        double mon=montoTotal * multiplo;
        movi.setMonto(mon);
        movi.setNumeroComprobante(compras.getPto()+"-"+compras.getNumero());
        movi.setSubTotal(compras.getGravado());
        movi.setFecha(fechaM);
        movi.setSaldo(mon);
        movi.setIdComprobante(id);
        FacturableE factu=new MovimientoProveedores();
        factu.guardar(movi);
        
        this.dispose();
        //JOptionPane.showMessageDialog(null, resultado);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void montoGravado_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoGravado_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;

            gravado = Numeros.ConvertirStringADouble(this.montoGravado_txt.getText());
            montrarMonto(gravado);
            this.alicuota_cmb.requestFocus();
        }
    }//GEN-LAST:event_montoGravado_txtKeyPressed

    private void otros_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otros_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double gravado;
            try {
                gravado = Numeros.ConvertirStringADouble(this.otros_txt.getText());
            } catch (NumberFormatException ex) {
                gravado = 0.00;
            }
            montrarMonto(gravado);
            this.jButton2.requestFocus();
        }
    }//GEN-LAST:event_otros_txtKeyPressed

    private void alicuota_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alicuota_cmbActionPerformed
        int posi=this.alicuota_cmb.getSelectedIndex();
        double gavado;
        switch(posi){
            case 0:
                gavado=Numeros.ConvertirStringADouble(this.montoGravado_txt.getText());
                gavado=gavado * 0.21;
                this.montoIva_txt.setText(String.valueOf(gavado));
                montrarMonto(gavado);
                alicuotaIva="0005";
                this.netoNoGravado_txt.requestFocus();
                break;
            case 1:
                gavado=Numeros.ConvertirStringADouble(this.montoGravado_txt.getText());
                gavado=gavado * 0.105;
                this.montoIva_txt.setText(String.valueOf(gavado));
                montrarMonto(gavado);
                alicuotaIva="0004";
                this.netoNoGravado_txt.requestFocus();
                break;
            case 2:
                gavado=Numeros.ConvertirStringADouble(this.montoGravado_txt.getText());
                gavado=gavado * 0.0;
                this.montoIva_txt.setText(String.valueOf(gavado));
                montrarMonto(gavado);
                alicuotaIva="0003";
                this.netoNoGravado_txt.requestFocus();
                break;
        }
    }//GEN-LAST:event_alicuota_cmbActionPerformed

    private void tipoComprobante_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoComprobante_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoComprobante_cmbActionPerformed

    private void montrarMonto(double agregar) {
        //System.err.println("DESCUENTO :"+cliT.getDescuento());

        double montoGravado = Numeros.ConvertirStringADouble(this.montoGravado_txt.getText());
        double montoIva = Numeros.ConvertirStringADouble(this.montoIva_txt.getText());
        
    double netoNoGravado=Numeros.ConvertirStringADouble(this.netoNoGravado_txt.getText());
    double exento=Numeros.ConvertirStringADouble(this.exento_txt.getText());
    double percepcionIva=Numeros.ConvertirStringADouble(this.percepcionIva_txt.getText());
    double impuestosNacionales=Numeros.ConvertirStringADouble(this.impuestosNacionales_txt.getText());
    double percepcionIb=Numeros.ConvertirStringADouble(this.percepcionIB_txt.getText());
    double impuestosMunicipales=Numeros.ConvertirStringADouble(this.impuestosMunicipales_txt.getText());
    double impuestosInternos=Numeros.ConvertirStringADouble(this.impuestosInternos_txt.getText());
    double otros=Numeros.ConvertirStringADouble(this.otros_txt.getText());

//montoTotal = montoTotal + agregar;
        montoTotal=montoGravado+montoIva+netoNoGravado+exento+percepcionIva+impuestosNacionales+percepcionIb+impuestosMunicipales+impuestosInternos+otros;

        String total1 = Numeros.ConvertirNumero(montoTotal);
        String total = "Total Comprobante : $ " + montoTotal;
        /*
    if(cliT.getTipoIva()==1){
        String bruto=Numeros.ConvertirNumero( montoTotal /1.21);
        String iva=Numeros.ConvertirNumero(montoTotal * 0.21);
        total="<html>Bruto :"+bruto+" <br>IVA 21% "+iva+" <br>Neto "+total1+"</html>";
    }else{
        total="<html>Neto "+total1+"</html>";
    }
         */
        //Double total=montoTotal * cliT.getDescuento();
        //comp.setMontoTotal(total);
        this.total_lbl.setText(total);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alicuota_cmb;
    private javax.swing.JTextField exento_txt;
    private datechooser.beans.DateChooserCombo fecha_cmb;
    private javax.swing.JTextField impuestosInternos_txt;
    private javax.swing.JTextField impuestosMunicipales_txt;
    private javax.swing.JTextField impuestosNacionales_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField montoGravado_txt;
    private javax.swing.JTextField montoIva_txt;
    private javax.swing.JTextField netoNoGravado_txt;
    private javax.swing.JTextField numero_txt;
    private javax.swing.JTextField otros_txt;
    private javax.swing.JTextField percepcionIB_txt;
    private javax.swing.JTextField percepcionIva_txt;
    private javax.swing.JTextField punto_txt;
    private javax.swing.JComboBox<String> tipoComprobante_cmb;
    private javax.swing.JLabel total_lbl;
    // End of variables declaration//GEN-END:variables
}
